#! /bin/zsh

#VAR
DBBOT_PID=$(ps -Ao "%p,%a" | grep 'python3 -u src/networking/active_server.py'| grep -v grep| cut -f1 -d ',')
cd "$(dirname "$0")"
cd ..

# Carry out specific functions when asked to by the system
case "$1" in
start)
echo "Starting db_bot"
echo $DBBOT_PID
if [ -z "$DBBOT_PID" ]; then
sudo bash -c 'nohup setsid python3 -u src/networking/active_server.py </dev/null >> log/active_server.log  2>&1 &'
echo "client is now in the house"
else
echo "client was already in the house"
fi
;;
stop)
echo "Stopping db_bot "
if [ ! -z "$DBBOT_PID" ]; then
sudo bash -c "kill -s SIGKILL $DBBOT_PID"
echo "client is no longer in the house"
else
echo "client was not in the house"
fi
;;
status)
if [ ! -z "$DBBOT_PID" ]; then
echo "client is in the house with pid = $DBBOT_PID"
else
echo "client is not in the house"
fi
;;
*)
echo "Usage: /etc/init.d/client {start|stop|status}"
exit 1
;;
esac

exit 0
